using System;
using System.Collections.Generic;
using System.Linq;
using CloudSyncUtil.Core.Configuration;
using CloudSyncUtil.Core.Integrations;
using Google.Apis.Drive.v3;
using Google.Apis.Drive.v3.Data;
using CloudSyncUtil.Core.FileSystem;

namespace CloudSyncUtil.Integrations.GoogleDrive
{
    public class GoogleCloudRepository:CloudRepository
    {
        protected readonly SettingsManager SettingsManager;

        protected string fieldsToFetch;

        // preserve sevice reference to make sure we dont ask for auth each time
        private DriveService googleDriveService;
        protected DriveService GoogleDriveService
        {
            get
            {
                if (googleDriveService == null)
                {
                    googleDriveService = this.Authorize() as DriveService;
                }
                return googleDriveService;
            }
        }

        public GoogleCloudRepository():this(SettingsManager.Instance)
        {

        }

        public GoogleCloudRepository(SettingsManager settingsManager)
            : base(new GoogleAuthorizationProvider(settingsManager), new GoogleFileMapper())
        {
            this.SettingsManager = settingsManager;
            
            this.ApiKey = ApiKeys.GoogleApiKey;
            this.ApiSecret = ApiKeys.GoogleApiSecret;

            this.UserName = this.SettingsManager.GoogleUserName();

            this.fieldsToFetch = this.SettingsManager.GoogleDefaultFetchFields();
        }

        public override CloudFile GetFile(string fileName, CloudFile parent = null)
        {
            var searchString = // get NOT folders NOT in trash
                  string.Format("mimeType!='application/vnd.google-apps.folder' and trashed=false and name='{0}'",
                      fileName);
            if (parent != null)
                searchString += string.Format(" and '{0}' in parents", parent.Id);

            var searchResult = this.GetFiles(searchString, 1);

            return searchResult.SingleOrDefault();
        }

        public override CloudFile GetFolder(string folderName, CloudFile parent = null)
        {
            var searchString = // get folders NOT in trash
                string.Format("mimeType='application/vnd.google-apps.folder' and trashed=false and name='{0}'",
                    folderName);

            if (parent != null)
                searchString += string.Format(" and '{0}' in parents", parent.Id);

            var searchResult = this.GetFiles(searchString, 1);

            return searchResult.SingleOrDefault();
        }

        public override bool HasFile(string fileName, CloudFile parent = null)
        {
            return this.GetFile(fileName, parent) != null ? true : false;
        }

        public override string GetFileMetadata(string fileName)
        {
            throw new NotImplementedException(); 
        }

        public override List<CloudFile> GetFiles(string search = "", int maxResults = 0)
        {
            var result = new List<CloudFile>();

            var list = GoogleDriveService.Files.List();

            list.Fields = fieldsToFetch;

            if (search != null)
            {
                list.Q = search;
            }

            var filesFeed = list.Execute();

            while (filesFeed.Files != null)
            {
                result.AddRange(this.FileMapper.MapMany(filesFeed.Files.ToList<object>()));

                // We will know we are on the last page when the next page token is null.
                // or we reached maximum results count
                // If this is the case, break.
                if (filesFeed.NextPageToken == null || (maxResults != 0 && result.Count >= maxResults))
                {
                    break;
                }

                // Prepare the next page of results
                list.PageToken = filesFeed.NextPageToken;
                // Execute and process the next page request
                filesFeed = list.Execute();
            }

            return result;
        }
        
        public override bool HasFolder(string folderName, CloudFile parent = null)
        {
            return this.GetFolder(folderName, parent) != null ? true : false;
        }

        public override CloudFile CreateFolder(string name, CloudFile parent = null)
        {
            CloudFile newDir = null;

            // Create metaData for a new Directory
            File body = new File();
            
            body.Name = name;
            body.Description = "Automatically generated by cloud sync util";
            body.MimeType = "application/vnd.google-apps.folder";
            
            if (parent != null)
            {
                body.Parents = new List<string> {parent.Id};
            }

            try
            {
                if (!this.HasFolder(name, parent))
                {
                    var request = GoogleDriveService.Files.Create(body);
                    
                    // fields that we need in future
                    request.Fields = "id";
                    request.Fields = "name";
                    
                    newDir = this.FileMapper.MapToFile(request.Execute());
                }
                else
                {
                    return this.GetFolder(name, parent);
                }
                    
            }
            catch (Exception e)
            {
                Console.WriteLine("An error occurred: " + e.Message);
            }

            return newDir;
        }

        public override CloudFile CreateFolderStructure(string path)
        {
            var folderStringArr = path.Split('/', '\\');

            CloudFile current = null;

            for (int i = 0; i < folderStringArr.Length; i++)
            {
                current = CreateFolder(folderStringArr[i].Trim(), current);
            }

            return current;
        }
        

        private string GetMimeType(string extension)
        {
            var mimeType = "application/unknown";

            var regKey = Microsoft.Win32.Registry.ClassesRoot.OpenSubKey(extension);

            if (regKey != null && regKey.GetValue("Content Type") != null)
                mimeType = regKey.GetValue("Content Type").ToString();

            return mimeType;
        }

        public override byte[] DownloadFile(string name)
        {
            var file = this.GetFile(name).InnerFile as File;
            if (file!=null && !string.IsNullOrEmpty(file.WebContentLink))
            {
                try
                {
                    var downloadRequest = GoogleDriveService.HttpClient.GetByteArrayAsync(file.WebContentLink);
                    return downloadRequest.Result;
                }
                catch (Exception e)
                {
                    Console.WriteLine("An error occurred: " + e.Message);
                }
            }
            return null;
        }

        public override CloudFile UploadFile(LocalFile file, CloudFile parent = null)
        {
            if (file == null)
                return null;

            if (this.HasFile(file.Name, parent))
            {
                var fileOnDrive = this.FileMapper.MapToFile(this.GetFile(file.Name, parent));

                if (fileOnDrive.MD5Checksum == file.MD5Checksum)
                {
                    return fileOnDrive;
                }
                else
                {
                    return this.UpdateFile(fileOnDrive, file, parent);
                }

            }

            var body = new File
            {
                Name = file.Name,
                Description = "Uploaded by CloudSyncUtil",
                MimeType = this.GetMimeType(file.Extension),
                Parents = new List<string> { parent.Id }
            };

            var byteArray = System.IO.File.ReadAllBytes(file.FullPath);

            using (var stream = new System.IO.MemoryStream(byteArray))
            {
                var request = googleDriveService.Files.Create(body, stream, body.MimeType);
                request.Upload();

                return this.FileMapper.MapToFile(request.ResponseBody);
            }
            return null;
        }

        public override CloudFile UpdateFile(CloudFile fileOnCloud, LocalFile file, CloudFile parent = null)
        {
            var body = new File
            {
                Name = file.Name,
                Description = "Uploaded by CloudSyncUtil",
                MimeType = this.GetMimeType(file.Extension),
                Parents = new List<string> { parent.Id }
            };

            var byteArray = System.IO.File.ReadAllBytes(file.FullPath);

            using (var stream = new System.IO.MemoryStream(byteArray))
            {
                var request = this.googleDriveService.Files.Update(body, fileOnCloud.Id, stream, body.MimeType);
                request.Upload();

                return this.FileMapper.MapToFile(request.ResponseBody);
            }

            return null;
        }
    }
}
